#!/bin/bash

unset DISPLAY

# Start wireshark via xpra
# To view wireshark, visit http://127.0.0.1:14500 in your browser (outside the container)
# If you are asked to enter a password, enter "wireshark"
echo "Starting Wireshark via xpra"
echo "To view, visit http://127.0.0.1:14500 in your browser (outside the container)"
echo "To stop this process, press Ctrl+C"
sleep 1
XPRA_PASSWORD=wireshark /usr/bin/xpra start --daemon=no --start-child='wireshark --fullscreen'


